config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pets
  # get "/pets/new", to: "pets#new"
  # post "/pets", to: "pets#create"

  # get "/pets", to: "pets#index"
  # get "/pets/:id", to: "pets#show", as: "pet"

  # get "/pets/:id/edit", to: "pets#edit", as: "pets_edit"
  # patch "/pets/:id", to: "pets#update"

  # delete "/pets/:id", to: "pets#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: %w(dog hamster cat turtle fish) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
    # redirect_to @pet
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostKitties</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name %>
    <%= f.input :species %>
    <%= f.input :address %>
    <%= f.submit "Submit" ,class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Lost Pets :c</h1>
<div class="container">
  <div class="row">
    <div class="col-6">
      <div>
      <% @pets.each do |pet| %>
        <h2><%= link_to pet.name, pet_path(pet) %></h2>
      <% end %>
      </div>
    </div>
  </div>

  <%= link_to "Add Pet", new_pet_path %>
</div>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2><%= @pet.species.capitalize %></h2>
<h3><%= @pet.address %></h3>
<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Delete", pet_path(@pet), method: :delete,
  data: { confirm: "Are you sure?"}
 %>
<%= link_to "Back to all", pets_path %>